language: android
jdk: oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
 global:
 - ANDROID_API=25
 - EMULATOR_API=25
 - ANDROID_BUILD_TOOLS=25.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes

script:
   - ./gradlew clean build

before_script: 
   - chmod +x gradlew

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"


addons:
  sonarqube:
    organization: "305"
script:
 - sonar-scanner
